export const FETCH_POSTS = 'FETCH_POSTS';
export const SET_POSTS = 'SET_POSTS';
export const SET_POSTS_ERROR = 'SET_POSTS_ERROR';
export const SET_POSTS_REQUEST = 'SET_POSTS_REQUEST';
export const SET_CURRENT_POST_ID = 'SET_CURRENT_POST_ID';
export const SET_CURRENT_POSTS = 'SET_CURRENT_POSTS';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_COMMENTS_ERROR = 'SET_COMMENTS_ERROR';
export const SET_COMMENTS_REQUEST = 'SET_COMMENTS_REQUEST';
